### PR TITLE
Fix mysql/mariadb dependency issue for CentOS 7. 

### PR DESCRIPTION
**Pull request by johnzimm**
The mysql module accounts for MariaDB.
Cleanup some of the install section case statements.

### CODE REVIEW

**Comment by johnzimm** [comment]
fixing an agent keys issue.  not quite ready to merge yet.

**Comment by johnzimm** [comment]
$::fqdn may not be guaranteed to be unique but is what I'm using for now.  A custom fact distributed with the module to generate $::uniqueid based on the certname would at least be unique within the puppet environment.  I'm not sure where $::uniqueid was coming from, but probably another module not in the dependency list.

**Comment by SyBernot** [comment]
I believe uniqueid originates in facter (there seems to be some flux with that fact and it seems abscent in facter 3.0) 
Perhaps UUID is what you want 
http://comments.gmane.org/gmane.comp.sysutils.puppet.user/5660
https://tickets.puppetlabs.com/browse/FACT-149
http://docs.puppetlabs.com/facter/3.0/core_facts.html#uuid

**Comment by johnzimm** [comment]
uuid would work.  I'll test and update.  It looks like uuid is not present in command line output even with facter --puppet flag.

**Comment by SyBernot** [comment]
I think it depends on the facter version, I don't think earlier versions of facter had UUID. 
on 1.62 there is no uuid on 2.4.1 there is, so mileage may vary but uuid is supported going forward where uniqueid seems deprecated in the later releases.

**Comment by johnzimm** [comment]
This appears to be working fine with the uuid change now.

I left this as three commits on the issue of MariaDB/MySQL.  I can split the pull request to two requests and squash the two uuid related commits to one if you like.

**Comment by djjudas21** [comment]
Thanks for the PR, sorry I took ages to review it. I've just had a baby and I've been off work for a few weeks. Is this now ready to merge, or are you still working on it?

Cheers,
Jonathan

**Comment by djjudas21** [comment]
I'm not happy to accept the to use `::uuid` since not all versions of Facter support it - I'm using Facter 2.4.4 on CentOS 6 and 7 and it doesn't have '::uuid`.

For what it's worth, I've never seen a Facter *without* `::uniqueid` so maybe different distros have different default facts packaged?

**Comment by coreone** [comment]
@johnzimm could really use this module, but we're running on CentOS7, so need this PR to make it functional...any chance of rebasing this PR and addressing the `::uniqueid` issue so this can get merged?

**Comment by johnzimm** [comment]
@coreone @djjudas21 Sorry.  I overlooked the messages from the end of September.  I'm applying this to CentOS 7 as well.  I'll take a look tomorrow at the uuid vs uniqueid issue and see if I can make sure it works for me and rebase.

@djjudas21 - Congrats on the new baby!

**Comment by johnzimm** [comment]
It looks like master was rebased?  Fixing my branch up now.

Also trying again to rundown uniqueid vs uuid.  I've moved completely to FOSS Puppet 4.2 and Facter 3.1.  uniqueid is definitely not there for me.

Looking at the core facts documentation...
 - Facter 1.6 has "uniqueid": https://docs.puppetlabs.com/facter/1.6/core_facts.html
 - Facter 2.4 (Puppet 3.8) has neither: http://docs.puppetlabs.com/facter/2.4/core_facts.html
 - Facter 3.x (Puppet 4.x) has "uuid": https://docs.puppetlabs.com/facter/3.1/core_facts.html

Here are a couple of related JIRA issues...
 - https://tickets.puppetlabs.com/browse/FACT-149
 - https://tickets.puppetlabs.com/browse/FACT-198

They talk about renaming uniqeuid to hostid, but I don't see a hostid fact.  If you've got either uniqueid, hostid or uuid facts for your hosts can you post some example values here?

A value for one of my hosts under facter 3.1 is...

```
    uuid => "42190A78-1CA5-7E53-441A-5F8F28BDBE8E"
```

The whole json block is...

```
dmi => {
  bios => {
    release_date => "04/14/2014",
    vendor => "Phoenix Technologies LTD",
    version => "6.00"
  },
  board => {
    manufacturer => "Intel Corporation",
    product => "440BX Desktop Reference Platform",
    serial_number => "None"
  },
  chassis => {
    asset_tag => "No Asset Tag",
    type => "Other"
  },
  manufacturer => "VMware, Inc.",
  product => {
    name => "VMware Virtual Platform",
    serial_number => "VMware-42 19 0a 78 1c a5 7e 53-44 1a 5f 8f 28 bd be 8e",
    uuid => "42190A78-1CA5-7E53-441A-5F8F28BDBE8E"
  }
}
```

**Comment by johnzimm** [comment]
Output above was on a CentOS 7 virtual machine.  One one of my CentOS 6 virtual machines I get uuid's attached to my block devices, but not in the dmi section.

```
dmi => {
  bios => {
    release_date => "04/14/2014",
    vendor => "Phoenix Technologies LTD",
    version => "6.00"
  },
  board => {
    manufacturer => "Intel Corporation",
    product => "440BX Desktop Reference Platform"
  },
  chassis => {
    asset_tag => "No Asset Tag",
    type => "Other"
  },
  manufacturer => "VMware, Inc.",
  product => {
    name => "VMware Virtual Platform"
  }
}
```
The uuid fact stored in puppetdb for the centos6 machine isn't one of the block devices though and appears to be as similar value as reported at the commandline on the centos7 machine.  The centos 7 machine output matches what is in puppetdb.

Still no uniqueid anywhere though.

**Comment by johnzimm** [comment]
I've rebased off of the current master and only included the changes for mysql/mariadb.  The uniqueid/uuid I will work on in a different branch and submit a pull request if I get that figured out definitively.

If this is acceptable please merge this pull request with just the one commit.

**Comment by djjudas21** [comment]
Thanks for rebasing and for your dev effort - this looks much better

**Pull request merged**
